---

# Support EOL Ubuntu versions upgrade to Trusty or Precise
# temporarily by replacing all occurences of the release
# shorthand name with the next nearest LTS version (i.e.
# saucy is replaced with trusty).
- name: Switch EOL versions to use the next LTS version in /etc/apt/sources.list
  replace: regexp={{ ansible_distribution_release }}
           replace={{ UBUNTU_BUMP_TABLE[ansible_distribution_version] }}
           backup=yes
           dest={{ SOURCE_LIST }}
  when: IS_EOL_AND_VULNERABLE
  sudo: True

- name: Update bash if we are vulnerable to shellshock (apt-based)
  apt: name=bash state=latest update_cache=yes
  when: WHEN_VULNERABLE
  sudo: True

- name: Revert /etc/apt/sources.list back to use EOL version
  replace: regexp={{ UBUNTU_BUMP_TABLE[ansible_distribution_version] }}
           replace={{ ansible_distribution_release }}
           dest={{ SOURCE_LIST }}
  when: IS_EOL_AND_VULNERABLE
  sudo: True
