---
- name: Upload shellshock test script
  copy: src=shellshock.sh dest={{ SHELLSHOCK_PATH }} mode=755

- name: Test if host is vulnerable to shellshock
  command: "{{ SHELLSHOCK_PATH }}"
  register: test_vuln
  ignore_errors: yes
  changed_when: WHEN_VULNERABLE

# Loading system package manager specific code (upgrade bash)
# based on the package manager rather than distribution
# since Amazon Linux will show "Amazon". Test against
# ansible_pkg_mgr is a lot easier and more accurate.
- include: apt-os.yml
  when: ansible_pkg_mgr == 'apt'

- include: yum-os.yml
  when: ansible_pkg_mgr == 'yum'

- name: Test if host is still vulnerable to shellshock after update
  command: "{{ SHELLSHOCK_PATH }}"
  register: test_vuln_again
  failed_when: STILL_VULNERABLE
  when: WHEN_VULNERABLE

- name: Remove shellshock script
  file: path={{ SHELLSHOCK_PATH }} state=absent
